//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.22 at 06:22:47 PM ICT 
//


package RestController;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element name="organisationName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="amount" type="{}paymentDetails"/&gt;
 *         &lt;element name="administrationFee" type="{}paymentDetails"/&gt;
 *         &lt;element name="vat" type="{}paymentDetails"/&gt;
 *         &lt;element name="total" type="{}paymentDetails"/&gt;
 *         &lt;element name="netTotal" type="{}paymentDetails"/&gt;
 *         &lt;element name="totalAmountReceived" type="{}paymentDetails"/&gt;
 *         &lt;element name="subscription" type="{}subscriptionDetails"/&gt;
 *         &lt;element name="address" type="{}address"/&gt;
 *         &lt;element name="details" type="{}invoiceDetails"/&gt;
 *       &lt;/all&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "invoiceInfo")
public class InvoiceInfo {

    @XmlElement(required = true)
    protected String organisationName;
    @XmlElement(required = true)
    protected PaymentDetails amount;
    @XmlElement(required = true)
    protected PaymentDetails administrationFee;
    @XmlElement(required = true)
    protected PaymentDetails vat;
    @XmlElement(required = true)
    protected PaymentDetails total;
    @XmlElement(required = true)
    protected PaymentDetails netTotal;
    @XmlElement(required = true)
    protected PaymentDetails totalAmountReceived;
    @XmlElement(required = true)
    protected SubscriptionDetails subscription;
    @XmlElement(required = true)
    protected Address address;
    @XmlElement(required = true)
    protected InvoiceDetails details;

    /**
     * Gets the value of the organisationName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrganisationName() {
        return organisationName;
    }

    /**
     * Sets the value of the organisationName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrganisationName(String value) {
        this.organisationName = value;
    }

    /**
     * Gets the value of the amount property.
     * 
     * @return
     *     possible object is
     *     {@link PaymentDetails }
     *     
     */
    public PaymentDetails getAmount() {
        return amount;
    }

    /**
     * Sets the value of the amount property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaymentDetails }
     *     
     */
    public void setAmount(PaymentDetails value) {
        this.amount = value;
    }

    /**
     * Gets the value of the administrationFee property.
     * 
     * @return
     *     possible object is
     *     {@link PaymentDetails }
     *     
     */
    public PaymentDetails getAdministrationFee() {
        return administrationFee;
    }

    /**
     * Sets the value of the administrationFee property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaymentDetails }
     *     
     */
    public void setAdministrationFee(PaymentDetails value) {
        this.administrationFee = value;
    }

    /**
     * Gets the value of the vat property.
     * 
     * @return
     *     possible object is
     *     {@link PaymentDetails }
     *     
     */
    public PaymentDetails getVat() {
        return vat;
    }

    /**
     * Sets the value of the vat property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaymentDetails }
     *     
     */
    public void setVat(PaymentDetails value) {
        this.vat = value;
    }

    /**
     * Gets the value of the total property.
     * 
     * @return
     *     possible object is
     *     {@link PaymentDetails }
     *     
     */
    public PaymentDetails getTotal() {
        return total;
    }

    /**
     * Sets the value of the total property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaymentDetails }
     *     
     */
    public void setTotal(PaymentDetails value) {
        this.total = value;
    }

    /**
     * Gets the value of the netTotal property.
     * 
     * @return
     *     possible object is
     *     {@link PaymentDetails }
     *     
     */
    public PaymentDetails getNetTotal() {
        return netTotal;
    }

    /**
     * Sets the value of the netTotal property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaymentDetails }
     *     
     */
    public void setNetTotal(PaymentDetails value) {
        this.netTotal = value;
    }

    /**
     * Gets the value of the totalAmountReceived property.
     * 
     * @return
     *     possible object is
     *     {@link PaymentDetails }
     *     
     */
    public PaymentDetails getTotalAmountReceived() {
        return totalAmountReceived;
    }

    /**
     * Sets the value of the totalAmountReceived property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaymentDetails }
     *     
     */
    public void setTotalAmountReceived(PaymentDetails value) {
        this.totalAmountReceived = value;
    }

    /**
     * Gets the value of the subscription property.
     * 
     * @return
     *     possible object is
     *     {@link SubscriptionDetails }
     *     
     */
    public SubscriptionDetails getSubscription() {
        return subscription;
    }

    /**
     * Sets the value of the subscription property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubscriptionDetails }
     *     
     */
    public void setSubscription(SubscriptionDetails value) {
        this.subscription = value;
    }

    /**
     * Gets the value of the address property.
     * 
     * @return
     *     possible object is
     *     {@link Address }
     *     
     */
    public Address getAddress() {
        return address;
    }

    /**
     * Sets the value of the address property.
     * 
     * @param value
     *     allowed object is
     *     {@link Address }
     *     
     */
    public void setAddress(Address value) {
        this.address = value;
    }

    /**
     * Gets the value of the details property.
     * 
     * @return
     *     possible object is
     *     {@link InvoiceDetails }
     *     
     */
    public InvoiceDetails getDetails() {
        return details;
    }

    /**
     * Sets the value of the details property.
     * 
     * @param value
     *     allowed object is
     *     {@link InvoiceDetails }
     *     
     */
    public void setDetails(InvoiceDetails value) {
        this.details = value;
    }

}
