
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.22 at 06:22:47 PM ICT 
//


package entity;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element name="organisationName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="amount" type="{}paymentDetails"/&gt;
 *         &lt;element name="administrationFee" type="{}paymentDetails"/&gt;
 *         &lt;element name="vat" type="{}paymentDetails"/&gt;
 *         &lt;element name="total" type="{}paymentDetails"/&gt;
 *         &lt;element name="netTotal" type="{}paymentDetails"/&gt;
 *         &lt;element name="totalAmountReceived" type="{}paymentDetails"/&gt;
 *         &lt;element name="subscription" type="{}subscriptionDetails"/&gt;
 *         &lt;element name="address" type="{}address"/&gt;
 *         &lt;element name="details" type="{}invoiceDetails"/&gt;
 *       &lt;/all&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "chinaInvoiceDetails")
public class ChinaInvoiceDetails {

    @XmlElement(required = true)
    protected String companyName;
    @XmlElement(required = true)
    protected String taxPayerIdentification;
    @XmlElement(required = true)
    protected String companyAddress;
    @XmlElement(required = true)
    protected String companyPhoneNumber;
    @XmlElement(required = true)
    protected String bankName;
    @XmlElement(required = true)
    protected String bankAccountNumber;
    @XmlElement(required = true)
    protected String deliveryAddress;
    @XmlElement(required = true)
    protected String contactName;
    @XmlElement(required = true)
    protected String contactPhoneNumber;

    public String getCompanyName() {
        return companyName;
    }

    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }

    public String getTaxPayerIdentification() {
        return taxPayerIdentification;
    }

    public void setTaxPayerIdentification(String taxPayerIdentification) {
        this.taxPayerIdentification = taxPayerIdentification;
    }

    public String getCompanyAddress() {
        return companyAddress;
    }

    public void setCompanyAddress(String companyAddress) {
        this.companyAddress = companyAddress;
    }

    public String getCompanyPhoneNumber() {
        return companyPhoneNumber;
    }

    public void setCompanyPhoneNumber(String companyPhoneNumber) {
        this.companyPhoneNumber = companyPhoneNumber;
    }

    public String getBankName() {
        return bankName;
    }

    public void setBankName(String bankName) {
        this.bankName = bankName;
    }

    public String getBankAccountNumber() {
        return bankAccountNumber;
    }

    public void setBankAccountNumber(String bankAccountNumber) {
        this.bankAccountNumber = bankAccountNumber;
    }

    public String getDeliveryAddress() {
        return deliveryAddress;
    }

    public void setDeliveryAddress(String deliveryAddress) {
        this.deliveryAddress = deliveryAddress;
    }

    public String getContactName() {
        return contactName;
    }

    public void setContactName(String contactName) {
        this.contactName = contactName;
    }

    public String getContactPhoneNumber() {
        return contactPhoneNumber;
    }

    public void setContactPhoneNumber(String contactPhoneNumber) {
        this.contactPhoneNumber = contactPhoneNumber;
    }
}
