//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.22 at 06:22:47 PM ICT 
//


package entity;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.sedex.spectrum.appsvc.payments.invoice package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.sedex.spectrum.appsvc.payments.invoice
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link InvoiceInfo }
     * 
     */
    public InvoiceInfo createInvoiceInfo() {
        return new InvoiceInfo();
    }

    /**
     * Create an instance of {@link ChinaPaymentDetails }
     * 
     */
    public ChinaPaymentDetails createPaymentDetails() {
        return new ChinaPaymentDetails();
    }

    /**
     * Create an instance of {@link SubscriptionDetails }
     * 
     */
    public SubscriptionDetails createSubscriptionDetails() {
        return new SubscriptionDetails();
    }

    /**
     * Create an instance of {@link Address }
     * 
     */
    public Address createAddress() {
        return new Address();
    }

    /**
     * Create an instance of {@link ChinaInvoiceDetails }
     * 
     */
    public ChinaInvoiceDetails createInvoiceDetails() {
        return new ChinaInvoiceDetails();
    }

}
